ibge-client:
  url: https://servicodados.ibge.gov.br/api/v1/localidades
  estados: ${ibge-client.url}/estados/

feign:
  httpclient:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types:
        - application/json
      min-request-size: 2048
    response:
      enabled: true